//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailing {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MailingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailingResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mailing.MailingResources", typeof(MailingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение аккаунта на сайте Лиги Разработчиков.
        /// </summary>
        internal static string ConfirmationMailCaption {
            get {
                return ResourceManager.GetString("ConfirmationMailCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поздравляем! Вы создали учетную запись на сайте Лиги Разработчиков!
        ///
        ///Теперь вы будете в курсе деятельности самой продуктивной организации программистов в МИСиС,а так же сможете оставить заказ!
        ///
        ///Чтобы начать, подтвердите Ваш электронный адрес, нажав на ссылку ниже.
        ///
        ///{0}
        ///
        ///
        ///Благодарим Вас за то, что присоединились к нашему сообществу!.
        /// </summary>
        internal static string ConfirmationMessageTemplate {
            get {
                return ResourceManager.GetString("ConfirmationMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mail@lod-misis.ru.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В Лиге Разработчиков произошло кое-что интересное!.
        /// </summary>
        internal static string NotificationMailCaption {
            get {
                return ResourceManager.GetString("NotificationMailCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здравствуйте!
        ///
        ///
        ///На сайте Лиги Разработчиков только что:
        ///
        ///{0}.
        /// </summary>
        internal static string NotificationMessageTemplate {
            get {
                return ResourceManager.GetString("NotificationMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на q4l7w1kzjVO9PErK5dkR.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление пароля на сайте Лиги Разработчиков.
        /// </summary>
        internal static string PasswordResetCaption {
            get {
                return ResourceManager.GetString("PasswordResetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здравствуйте!
        ///
        /// На сайте Лиги Разработчиков было запрошено восстановление пароля на учетную запись, привязанную к Вашему e-mail.
        ///
        ///Ссылка для восстановления пароля: {0}
        ///
        ///Если же вы не запрашивали восстановления пароля - просто проигнорируйте это письмо..
        /// </summary>
        internal static string PasswordResetMessageTemplate {
            get {
                return ResourceManager.GetString("PasswordResetMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 25.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на smtp.yandex.ru.
        /// </summary>
        internal static string SmtpServer {
            get {
                return ResourceManager.GetString("SmtpServer", resourceCulture);
            }
        }
    }
}
